import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactFlowProvider from "./ReactFlowProvider";
import "reactflow/dist/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex w-full h-screen"}>
        <ReactFlowProvider>
          {children}
        </ReactFlowProvider>
      </body>
    </html>
  );
}
